# Generated by Django 4.2.19 on 2025-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrients',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
