# Generated by Django 4.2.19 on 2025-03-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_remove_nutrients_ingredient_ingredient_nutrient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='nutrient',
        ),
        migrations.AddField(
            model_name='nutrients',
            name='ingredient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.ingredient'),
        ),
    ]
