# Generated by Django 4.2.19 on 2025-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_predictedresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedresult',
            name='practice_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='predictedresult',
            name='restTime',
            field=models.DurationField(),
        ),
    ]
