# Generated by Django 4.2.19 on 2025-03-30 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_alter_predictedresult_practice_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='practice_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
