# Generated by Django 4.2.19 on 2025-03-30 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_session_practice_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultofsession',
            name='cardio',
        ),
        migrations.RemoveField(
            model_name='resultofsession',
            name='liftable_weight',
        ),
        migrations.RemoveField(
            model_name='resultofsession',
            name='total_rep',
        ),
        migrations.RemoveField(
            model_name='session',
            name='practice_time',
        ),
        migrations.AddField(
            model_name='resultofsession',
            name='practice_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
