# Generated by Django 4.2.19 on 2025-03-30 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_remove_resultofsession_cardio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultofsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
