# Generated by Django 4.2.19 on 2025-03-31 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultofsession',
            name='workout_notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='HealthDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('calo_burned', models.IntegerField(default=0)),
                ('calo_intake', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('ingredient', models.ManyToManyField(to='health.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
