# Generated by Django 4.2.19 on 2025-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_resultofsession_workout_notes_healthdiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='ingredient',
            field=models.ManyToManyField(blank=True, null=True, to='health.ingredient'),
        ),
    ]
