# Generated by Django 4.2.19 on 2025-04-17 07:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_healthdiary_bmi_healthdiary_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupschedule',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
