# Generated by Django 4.2.19 on 2025-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_groupschedule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.IntegerField(null=True),
        ),
    ]
