# Generated by Django 4.2.19 on 2025-04-26 19:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
